---
# tasks file for squid

- name: install squid
  apt:
    name:
      - squid
      - apache2-utils
      - python3-pip
    state: present
    update_cache: yes

- name: copy squid config
  template:
    src: squid.conf.j2
    dest: "/etc/squid/squid.conf"
  notify: restart squid

- name: start squid
  service:
    name: squid
    state: started
    enabled: true

- name: install passlib for htpasswd
  pip:
    name: passlib
    state: present

- name: create admin accaunt
  community.general.htpasswd:
    path: /etc/squid/passwd
    name: "{{ username }}"
    password: "{{ password }}"
    state: present